version: "3"
services:
  backend:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    volumes:
      - ./backend:/app:cached
      - backend_node_modules:/app/node_modules
    command: sh -c "npm run db:migrate:init && npm run start"
    ports:
      - 3500:3500
    environment:
      DATABASE_URL: mysql://root:root@db:3306/react_training
      TEST_DATABASE_URL: mysql://root:root@db:3306/react_training_test
    depends_on:
      - db
  db:
    image: mysql:8.0.25
    environment:
      MYSQL_ROOT_PASSWORD: root
      TZ: "Asia/Tokyo"
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - 3306:3306
    volumes:
      - ./mysql:/var/lib/mysql
      - ./docker/db:/etc/mysql/conf.d
volumes:
  backend_node_modules:
